[tool.poetry]
name = "PyroBot"
version = "1.0.0"
description = "A template which I use to make my telegram bots!"
authors = ["Divkix <techdroidroot@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
Pyrogram = "^1.2.9"
TgCrypto = "^1.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
